---
title: "Worksheets: Review a species richness analysis"
format: typst
filters:
  - include-code-files
---

Suppose a fellow student asked you to review their species richness analysis.
**Indeed, it contains a mistake!**

As you review their report, *discover how symbols and text convey formatting and the structure of the document*.
On the following pages is first a plain text file, `analysis.qmd` (in a single grey box), and then the same file is converted to a formatted PDF (using *Typst*) on the next page.
You will compare the two documents to investigate which parts of the plain text are interpreted as formatting and how natural language and R code are intermixed.

# Exercise

1.  Take a highlighter and mark all the text in `analysis.qmd` that does not appear in the output document.
    Then look at the PDF and mark everything not present in `analysis.qmd`.

2.  Formatting in this PDF includes different levels of headings and *emphasized* (in italics) and **strong** statements (in bold).
    What parts of `analysis.qmd` convey the formatting information for these elements?

3.  Can you find the R output of the analysis in one of the paragraphs in the PDF?
    There are two ways in which code is integrated into `analysis.qmd`.
    What are they, and how do they differ?

4.  **Bonus: Did you uncover the error in the analysis?**

    ---
    If you have enough time in class, continue with the questions below. Otherwise, answer them at home.
    ---

5.  The output document has a table referenced in the text.
    What are the two components necessary for creating the reference?

6.  At the beginning of `analysis.qmd` is a section fenced by `---`.
    What do you believe this section is for, and do you notice anything special about how the information is organized?
    Now compare with the lines starting with `#|`.
    Do you notice any similarities or differences?

7.  There are two blocks fenced by ```` ```{r} ```` and ```` ``` ```` in `analysis.qmd`, but only one of them appears in the output.
    How is this controlled?

{{< pagebreak >}}

## `analysis.qmd`

``` {include="analysis.qmd" filename="analysis.qmd"}
```
