# Class Meeting 14A

We will summarize the contents of the course and -- for those of you interested in learning more about computer and/or data science -- suggest some directions in which you might go.

<div>
<iframe src="../../Lec20_Summary.pdf" width="100%" height="600px" frameBorder="0"> </iframe>
</div>

[Download the Slides from today](https://github.com/ubc-cs/cpsc203/raw/main/files/Lec20_Summary.pdf)

## Links for today

- If you are continuing at UBC next year, then browse through these lists for computer science and/or data science related courses that you can take after CPSC 203:
  - [CPSC course descriptions](https://vancouver.calendar.ubc.ca/course-descriptions/subject/cpscv).
  - [DSCI course descriptions](https://vancouver.calendar.ubc.ca/course-descriptions/subject/dsciv).
- Data science programs for undergraduates at UBC Vancouver:
  - The [minor](https://datascience.ubc.ca/minor).
  - The (brand new!) [major](https://datascience.ubc.ca/major).
- Programs for students who have completed or are about to complete an undergraduate degree:
  - The [Bachelors of Computer Science (BCS)](https://www.cs.ubc.ca/students/undergrad/degree-programs/bcs-program-second-degree), which is a two-year, second degree program for students who wish they had chosen computer science the first time.
  - The [Masters of Data Science (MDS)](https://masterdatascience.ubc.ca/), which is a one-year professional program for students wishing to find industry careers in data science.
- [xkcd comics](https://xkcd.com).
  - Matplotlib extension for [xkcd-like plots](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.xkcd.html).

## Logistics

No (new) code for today.
