---
title: "{{< var course.full-title >}}"
subtitle: "{{< var instructor.name >}}"
listing:
  id: most-recent-announcement
  contents: posts
  sort: "date desc"
  type: default
  max-items: 1
  fields: [title, subtitle, description, date, image, reading-time]
execute:
  freeze: false
---

:::::: columns
::: {.column width="75%"}
Welcome to the webpage for {{< var course.code >}}!
:::

::: {.column width="5%"}
:::

::: {.column width="20%"}
{{< qrcode https://ubc-cs.github.io/cpsc203 >}}
:::
::::::

## Course information

**Instructor:** {{< var instructor.name >}} ({{< var instructor.pronouns >}})\
**Time:** {{< var course.time >}}\
**Location:** {{< var course.location >}}

## Most recent announcement

::: {#most-recent-announcement}
:::

```{r}
#| label: setup
#| echo: false
#| message: false

library(conflicted)
library(dplyr)
conflicts_prefer(dplyr::filter)
library(fontawesome)
library(fs)
library(glue)
library(gt)
library(gtExtras)
library(here)
library(lubridate)
library(readr)
library(stringr)
library(tidyr)

# Generate ids for each link to join into schedule
resources_paths <-
  c(
    path("slides")
  )

resources <-
  tibble(
    path = dir_ls(resources_paths, glob = "*.qmd"),
    week = path |> path_file() |> str_extract("^(\\d+).*$", group = 1),
    day = path |>
      path_file() |>
      str_extract("\\d+_([:alpha:]+)_.*$", group = 1),
    type = path |> path_dir()
  ) |>
  # Remove unassigned resources indicated by "tbd"
  filter(!str_detect(path, "tbd")) |>
  select(week, type, day, path) |>
  pivot_wider(names_from = c(day, type), names_sep = "_", values_from = path)

schedule <- read_csv(here("data", "schedule.csv"), show_col_types = FALSE) |>
  left_join(resources, by = join_by(week), na_matches = "never") |>
  relocate(tue_slides, .before = tue_activity) |>
  relocate(thu_slides, .before = thu_activity)
```

```{r}
#| label: schedule
#| echo: false

current_date <- today()

monday_of_current_week <-
  max(
    min(schedule$date, na.rm = TRUE),
    schedule$date[schedule$date <= current_date],
    na.rm = TRUE
  )

next_exam_within_12_days <-
  max(
    min(schedule$date, na.rm = TRUE),
    schedule$exam_due[schedule$exam_due <= current_date + days(12)],
    na.rm = TRUE
  )

schedule |>
  mutate(
    # Show only resources for exams within 12 days or earlier
    exam = if_else(
      exam_due <= next_exam_within_12_days,
      glue("[{exam}](https://us.prairietest.com)", .na = NULL),
      exam
    ),
    exam_practice = if_else(
      exam_due <= next_exam_within_12_days,
      exam_practice,
      NA
    ),
    # Remove any resources from future weeks
    across(
      starts_with(c("tue", "thu", "lab", "potw")),
      \(column) if_else(date <= monday_of_current_week, column, NA)
    )
  ) |>
  select(!c(part)) |>
  gt(
    # groupname_col = "part"
  ) |>
  fmt_date(
    date,
    date_style = "MMMd"
  ) |>
  sub_missing(
    missing_text = ""
  ) |>
  fmt_url(
    columns = ends_with("slides"),
    label = fa("window-maximize")
  ) |>
  sub_missing(
    columns = ends_with("slides"),
    missing_text = fa("window-maximize", fill_opacity = 0.1)
  ) |>
  fmt_url(
    columns = ends_with("activitiy"),
    label = fa("file-alt")
  ) |>
  sub_missing(
    columns = ends_with("activity"),
    missing_text = fa("file-alt", fill_opacity = 0.1)
  ) |>
  fmt_url(
    columns = ends_with("video"),
    label = fa("circle-play")
  ) |>
  sub_missing(
    columns = ends_with("video"),
    missing_text = fa("circle-play", fill_opacity = 0.1)
  ) |>
  fmt_url(
    columns = lab,
    label = fa("laptop-code")
  ) |>
  sub_missing(
    columns = lab,
    missing_text = fa("laptop-code", fill_opacity = 0.1)
  ) |>
  fmt_url(
    columns = potw,
    label = fa("calendar-week")
  ) |>
  sub_missing(
    columns = potw,
    missing_text = fa("calendar-week", fill_opacity = 0.1)
  ) |>
  fmt_url(
    columns = exam,
    rows = exam_due <= next_exam_within_12_days,
    show_underline = FALSE
  ) |>
  fmt_date(
    exam_due,
    date_style = "MMMd"
  ) |>
  fmt_url(
    columns = exam_practice,
    label = fa("pen-to-square")
  ) |>
  sub_missing(
    columns = exam_practice,
    missing_text = fa("pen-to-square", fill_opacity = 0.1)
  ) |>
  cols_label(
    week = "Week",
    date = "Mon",
    tue_slides = "S",
    tue_activity = "A",
    tue_video = "V",
    thu_slides = "S",
    thu_activity = "A",
    thu_video = "V",
    lab = "Lab",
    potw = "POTW",
    exam = "Book",
    exam_due = "Due",
    exam_practice = "Practice"
  ) |>
  tab_spanner(
    label = "Tue",
    columns = starts_with("tue")
  ) |>
  tab_spanner(
    label = "Thu",
    columns = starts_with("thu")
  ) |>
  tab_spanner(
    label = "Examlet",
    columns = c(exam, exam_due, exam_practice)
  ) |>
  cols_align(
    align = "center",
    columns = c(lab, potw, exam_practice)
  ) |>
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = list(
      cells_row_groups(),
      cells_stubhead(),
      cells_column_labels(),
      cells_column_spanners()
    )
  ) |>
  gt_highlight_rows(
    row = date == monday_of_current_week,
    fill = "#ccefff"
  ) |>
  tab_options(
    quarto.disable_processing = TRUE,
    table.width = "100%"
  )
```
