---
title: "Setup: Tech stack"
---

````{=html}
<!--
Any Quarto includes (https://quarto.org/docs/authoring/includes.html) with specific OS instructions should use the following tabset group (https://quarto.org/docs/output-formats/html-basics.html#tabset-groups):

```
::: {.panel-tabset group="os"}
## Windows

<windows-specific-instructions>

## macOS

<macos-specific-instructions>
:::
```
-->
````

As with any computer science or data science course, several tools and software packages are needed for this course.
These tools are not used by the typical consumer, so most Windows or macOS installations will not include them.
Even on machines which do include them (such as many Linux distributions), they may still need some configuration.
Below you will find guides to install the *tech stack* for {{< var course.code >}}, with different guides for different operating systems.
A tech stack is the complete set of tools and technologies needed to accomplish a particular task; in this case, it is the various programming and data analytics that we will explore in {{< var course.code >}}.

As you go through the install guides, remember that perhaps the two most important things you will learn in this course is how to troubleshoot things and achieve familiarity and proficiency with your computer.
Be patient, read things carefully, do not be afraid to try things, it's unlikely you will do anything to irreversibly break your computer!
Almost everything you do (you're on your own if you decide to take a hammer to your laptop!) can be undone, don't be afraid to ask your peers, TAs, and the instructor on Giscus below (you will need to set up an GitHub account first).

This is an exciting time for you as you begin your Software Development journey!

## Hardware

Before starting, ensure that your laptop meets the minimum requirements:

-   Can connect to networks via a wireless connection.
-   Has at least 25 GB disk space available.
-   Has at least 4 GB of RAM (more is recommended).
-   Uses a 64-bit CPU.
-   Is at most 6 years old at the start of the course (4 years old or newer is recommended).
-   Student user has full administrative access to the computer.

::: callout-important
If your computer does not meet any of the requirements above, please don't just drop the course!!
Let me know first and we can discuss alternate possibilities so you can still take the course.
:::

## Software

::: callout-tip
These installation notes assume you are starting with a fresh install, without any custom setups.
Following the instructions below will help you install and configure the tech stack correctly in the same way for our course, enabling us to support you effectively and minimize setup issues and software conflicts.
:::

::: {.panel-tabset group="os"}
## Windows

[In all the sections below, if you are presented with the choice to download either a 64-bit (also called x64) or a 32-bit (also called x86) version of the application **always** choose the 64-bit version.]{#intel-versions}
{{< contents intel-versions >}}

## macOS

{{< contents intel-versions >}} If you purchased a Mac anytime in the last few years, chances are you have an "M1/M2/M3/M4"...
Mac, also known as "Apple Silicon", and "arm64".
When given the option, you should choose to download the "arm64"/Apple Silicon or the "Universal versions---if that choice doesn't exist, then you can choose the "x86" version which will run in "emulated mode", which will result in a slight performance penalty.
:::

```{=html}
<!--
Quarto includes for software should start with a level 3 heading `### <software-name>`
-->
```

{{< include /includes/software/_os.qmd >}}

{{< include /includes/software/_terminal.qmd >}}

{{< include /includes/software/_package-manager.qmd >}}

{{< include /includes/software/_python.qmd >}}

## Optional software

If you are interested in using a very common software development tool and platform for version control, check out Git and GitHub. We also have two examples with Zoom or your web browser on how to install and update everyday software with a package manager.

{{< include /includes/software/_git-and-github.qmd >}}

{{< include /includes/software/_zoom.qmd >}}

{{< include /includes/software/_web-browser.qmd >}}

## Attribution

These instructions have been adapted and remixed from the original version provided by the UBC-Vancouver [MDS Install stack](https://ubc-mds.github.io/resources_pages/installation_instructions/) under a CC-BY-SA 4.0 license.
They were originally written by [Anmol Jawandha](https://github.com/Anmol6) but have since been updated by Stephan Koenig, Firas Moosvi, Joel Ostblom, Tomas Beuzen, Rodolfo Lourenzutti, Tiffany Timbers, and others.

-   [Harvard CS109](http://cs109.github.io/2015/)
-   [UBC STAT 545](http://stat545.com/packages01_system-prep.html#mac-os-system-prep) licensed under the [CC BY-NC 3.0](https://creativecommons.org/licenses/by-nc/3.0/legalcode).
-   [Software Carpentry](https://software-carpentry.org/)
-   [Oracle - How do I set or change the `PATH` system variable?](https://www.java.com/en/download/help/path.xml)
-   [Numerical Methods - Getting started](https://clouds.eos.ubc.ca/~phil/numeric/python.html)
-   [EDUCE setup instructions](https://educe-ubc.github.io/index.html)
